theme: jekyll-theme-cayman
title: Bottle Detection in the Wild Using Low-Altitude Unmanned Aerial Vehicles

description: Jinwang Wang, Wei Guo, Ting Pan, Huai Yu, Wen Yang

show_downloads: true

mathjax: true
markdown: kramdown
